default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.4
    hooks:
      - id: shellcheck
      - id: shfmt
        args: [-i 4]

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        require_serial: false
        language: system
        types: [python]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.5.5
    hooks:
      - id: isort
        require_serial: false
        language: system
        types: [python]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        require_serial: false
        language: system
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy
        require_serial: false
        language: system
        types: [python]
